services:
  - type: web
    name: eshasilk-backend
    env: docker
    context: .
    plan: free
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: database_url
        fromDatabase:
          name: eshasilk-db
          property: connectionString
    disk:
      name: uploads-disk
      mountPath: /var/www/html/public/uploads
      sizeGB: 1

databases:
  - name: eshasilk-db
    databaseName: eshasilk
    user: eshasilk
    plan: free
